### ISSUE TITLE
behavior without GPS enabled

### ISSUE THREAD

**Issue by balcy** [patrickjane/ut-scooter#2]
first of all thank you for the app, I've been able to do rides with it already.
What I noticed is that without location access most API calls (the profile related ones, too) seem to fail.
E.g. if you click on Settings->Bird->Profile you get a bad request error.
Maybe in this case the app should not to try to call the API, but make the profile button not enabled, or return a 'location access needed' message.

I think the same problems happened for me when adding the provider first: The confirmation code email was sent each time, but when entering it there was an error.

That you need location for seeing the scooters on the map is clear, but it might not be known that you need it when you add an account. So it might be better disabling adding accounts without GPS.

**Comment by balcy** [comment]
![screenshot20210822_113004033](https://user-images.githubusercontent.com/848115/130350355-b173309b-cb87-4692-84b2-f448f6ca58bd.png)

**Comment by patrickjane** [comment]
@balcy Good point, I have disabled the profile button while GPS is unavailable, gonna push an updated version to the store.

However, during account setup, no GPS is required. So I think that must have been a different issue. Can you supply the error message you got when you tried to enter the confirmation code?

**Comment by balcy** [comment]
ah right, it might be another issue:
![image](https://user-images.githubusercontent.com/848115/130483665-b034a3fd-25c5-4013-a566-1633f9e6eab2.png)
![image](https://user-images.githubusercontent.com/848115/130483759-4842d961-8196-44c9-b4e3-fdce209a6507.png)

So first I entered the email address and each time the confirmation code was received.
I tried to enter it manually (opened the email on the laptop), but several times it was not successful.
In the end I opened the email in the browser on the phone, and directly pasted the confirmation code, which worked.

I thought I might have been too slow when entering the code.

**Comment by patrickjane** [comment]
Ok I would expect something like 403 or 401 when the confirmation code is wrong; but it seems like the Bird servers give you 404.

Well I think the reason is that you somehow got the code wrong. I have no API documentation for the endpoints so I can only guess, and cannot implement any proper error handling either (this is why the notification spits out technical error infos). I don't think its an issue with the app; its just the way bird reports errors in this case.

**Comment by patrickjane** [comment]
Pushed an update which disabled profile access for bird as long as no gps signal is available. 

166ba99ea843e09c908e652001a4b918485d24c0
