### ISSUE TITLE
Add support for other scooters

### ISSUE THREAD

**Issue by invertedEcho** [patrickjane/ut-scooter#7]
Hello, it probably would be possible to add support for other e-scooters, right?
I would appreciate it if Lime would get added.

**Comment by xdub** [comment]
It would probably be possible to add Lime. https://github.com/ubahnverleih/WoBike/blob/master/Lime.md

**Comment by patrickjane** [comment]
If you take a look at your link, you will note that the documented API does not offer any form of scooter unlocking/ride starting.

This applies to most, if not all of their documented APIs (did not check all of them).

I knew this site already, but it is of no use unless there is an API endpoint for actually starting a ride.


The Scooter app is designed to support several providers, and it will be rather easy and quick to add support for new providers. However, the thing which makes it difficult is that none (I repeat: none) of the providers agree to share API documentation. Therefore, it is impossible to implement provider support, unless someone reverse-engineers the API. This has been done for Bird and NextBike, therefore I was able to implement support for it.

If you come across complete API documentations for other providers, let me know, and I will happily implement it.
